CREATE TABLE parametros(TIMESTAMP INT PRIMARY KEY NOT NULL, NOMBRE VARCHAR(10) NOT NULL,VALOR VARCHAR(15) NOT NULL);
CREATE TABLE tempext(TIMESTAMP INT PRIMARY KEY NOT NULL, VALOR FLOAT NOT NULL);
CREATE TABLE humext(TIMESTAMP INT PRIMARY KEY NOT NULL, VALOR FLOAT NOT NULL);
CREATE TABLE tempagua(TIMESTAMP INT PRIMARY KEY NOT NULL, VALOR FLOAT NOT NULL);
CREATE TABLE ph(TIMESTAMP INT PRIMARY KEY NOT NULL, VALOR FLOAT NOT NULL);